# A sample Gemfile
source "https://rubygems.org"
gem 'sinatra'
gem 'thin'
gem 'foreman'

group :development do
  gem 'awesome_print'
  gem 'shotgun'
  gem 'guard'
  gem 'guard-livereload'
  gem 'rb-fsevent'
  gem 'compass'
  gem 'bootstrap-sass'
end
# gem "rails"
